import type { GetServerSideProps, NextPage } from 'next'
import { getSession, signOut } from 'next-auth/react'
import Head from 'next/head'
import { BiCreditCardAlt, BiCard, BiLogOut } from 'react-icons/bi';
import { useEffect, useState } from 'react'
import { useAuth } from '../contexts/auth'
import styles from '../styles/Home.module.scss'
import Voucher from '../components/shopVoucher/voucher';
import OrderHistory from '../components/orderHistory/orderHistory';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const [menu, setMenu] = useState<number>(0)

  const user = useAuth()
  const router = useRouter()

  useEffect(() => {
    const { state } = router.query
    if (state) {
        setMenu(Number(state))
    } else {
        setMenu(0)
    }
}, [router.query])

  const renderView = () => {
    switch (menu) {
      case 0:
        return <Voucher />
      case 1:
        return <OrderHistory />

      default:
        return <Voucher />
    }
  }

  return (
    <>
      <Head>
        <title>Khách hàng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.home}>

        <div className={styles.sidebar}>
          <div className={styles.user}>
            <div className={styles.user__avatar}>
              <h5>
                {user ? user.name[0] : 'IStore'}
              </h5>
            </div>
            <div className={styles.user__username}>
              @{user ? user.username : 'IStore'}
            </div>
            <div className={styles.user__name}>
              {user ? user.name : 'IStore'}
            </div>
          </div>
          <hr />
          <div className={styles.menu}>
            <div
              className={styles['menu-item'] + " " + (menu === 0 ? styles['menu-item--active'] : "")}
              onClick={() => router.push('/')}
            >
              <div className={styles['menu-item__icon']}>
                <BiCreditCardAlt />
              </div>
              <div className={styles['menu-item__label']}>
                Voucher cá nhân
              </div>
            </div>
            <div
              className={styles['menu-item'] + " " + (menu === 1 ? styles['menu-item--active'] : "")}
              onClick={() => router.push('/?state=1')}
            >
              <div className={styles['menu-item__icon']}>
                <BiCard />
              </div>
              <div className={styles['menu-item__label']}>
                Lịch sử mua hàng
              </div>
            </div>
            <hr />
            <div 
              className={styles['menu-item']}
              onClick={() => signOut()}
            >
              <div className={styles['menu-item__icon']}>
                <BiLogOut />
              </div>
              <div className={styles['menu-item__label']}>
                Đăng xuất
              </div>
            </div>
          </div>
        </div>

        <div className={styles.content}>
          {renderView()}
        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    const session = await getSession(context)

    if (!session) throw new Error()

    return {
      props: {}
    }

  } catch (error) {
    return {
      redirect: {
        permanent: false,
        destination: '/auth'
      }
    }
  }
}

export default Home
